version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    reviewers:
      - Jarmos-san

  - package-ecosystem: "gomod"
    directory: "./server/v2"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    reviewers:
      - Jarmos-san

  - package-ecosystem: "npm"
    directory: "./docs"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(docs): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    reviewers:
      - Jarmos-san
